import json
from pathlib import Path
P = {p['id']: f"{p['paper']} {p['passage']}" for p in json.load(open('六级/仔细阅读/passages.json', encoding='utf-8'))}
D = [
('s01', 'The classes he had planned teaching computer skills to aspiring young professionals were canceled', 'The classes he had planned, teaching computer skills to aspiring young professionals, were canceled', '不加逗号会读成 had planned teaching（plan 不接动名词）；teaching… 是修饰 classes 的插入成分'),
('s02', 'against Stability AL,', 'against Stability AI,', '公司名拼错：第 2 段和第 46 题都是 Stability AI'),
('s02', 'without permission by the original creators', 'without permission from the original creators', 'permission 的来源用 from'),
('s02', 'make a blanket statement about all works in a dataset as being applicable', 'make a blanket statement that all works in a dataset are covered', 'make a statement about X as being Y 不是规范结构，applicable 也缺对象；上句说训练数据 is covered by 合理使用'),
('s03', 'criminal conducts', 'criminal conduct', 'conduct（行为）是不可数名词'),
('s03', 'As an adult, I too, struggle', 'As an adult, I, too, struggle', '插入语 too 两侧逗号要成对，否则逗号隔开了主语和谓语'),
('s03', 'the settings in their kids’ phone', 'the settings in their kids’ phones', '家长、孩子都是复数，手机应为复数'),
('s03', 'real-world dangers, but all the ones sneaking online', 'real-world dangers, but also about all the ones sneaking online', 'don’t just … but 的后半缺 about，前后不平行'),
('s04', 'to continue to accomplish progress', 'to continue to make progress', '搭配：make progress（accomplish 不接 progress）'),
('s05', 'But, instead of reining in the use of tax havens', 'But, instead of the plan reining in the use of tax havens', '悬垂结构：instead of reining in 的逻辑主语成了 the problem；补出上句的 the plan'),
('s05', 'factories and research in that country', 'factories and research in those countries', '指代的是复数 tax havens'),
('s05', 'of total corporate revenue in 2019', 'of total corporate tax revenue in 2019', '逻辑/事实：流失的企业税占的是全球企业税收入的 10%，不是企业营收'),
('s05', 'signed onto in 2021', 'signed on to in 2021', 'sign on to（短语动词 + 介词）应分写'),
('s05', 'is necessary in reversing', 'is necessary for reversing', 'necessary for doing'),
('s05', 'by the governments where they operate and create value', 'by the governments where the corporations operate and create value', 'they 没有合适的先行词（profits 不能 operate）'),
('s07', 'In the process, they reduce us', 'In the process, it reduces us', '指代上句单数主语 a significant proportion of digital tech'),
('s07', 'trading convenience to the point where', 'trading for convenience to the point where', 'trade X 是“拿 X 去换”，原文意思反了；应为“为了便利而交换（自主权）”'),
('s09', 'the situation will likely diffuse much faster', 'the situation will likely be defused much faster', '缓和紧张局面是 defuse，diffuse 是扩散'),
('s09', 'for doing what they are doing to avoid unnecessary conflict', 'for doing what they are doing, to avoid unnecessary conflict', '不加逗号，to avoid… 会被读成对方行为的目的'),
('s10', 'individuality and autonomy is sacrificed', 'individuality and autonomy are sacrificed', 'and 连接两个不同概念作主语，谓语用复数'),
('s11', 'disputes over the climate change', 'disputes over climate change', 'climate change 泛指，不加冠词'),
('s11', 'more inclusive nation; and in the words of Martin Luther King Jr., “A society at peace', 'more inclusive nation—in the words of Martin Luther King Jr., “a society at peace', '分号后的 and in the words of… 不是完整分句；引语是 nation 的同位语'),
('s12', 'an example of collectivism, threatened the dream', 'an example of collectivism, threatens the dream', 'It argues 引出的一般性主张，用现在时'),
('s12', 'to be complacent to the inevitable end', 'to be complacent about the inevitable end', '搭配：complacent about'),
('s12', '“Don’t worry about losing friendships, just focus on study', '“Don’t worry about losing friendships; just focus on study', '逗号连接两个祈使分句（comma splice）'),
('s13', 'if the 1980s trend continued, we would have been', 'if the 1980s trend had continued, we would have been', '与过去事实相反的虚拟条件用 had continued'),
('s13', 'at lower rates than the men.', 'at lower rates than the men’s.', '比较对象应是男性的工资'),
('s13', 'slip behind their male counterparts.', 'slip behind their male counterparts’.', '比较对象应是男性同行的薪水'),
('s14', 'It isn’t the goods themselves we seek, it is the love', 'It isn’t the goods themselves we seek; it is the love', '逗号连接两个独立分句（comma splice）'),
('s14', 'condemn them for their greed, we should pity them', 'condemn them for their greed; we should pity them', '逗号连接两个独立分句（comma splice）'),
('s14', 'their timid regimented minds', 'their timid, regimented minds', '并列形容词之间加逗号'),
('s14', 'that might be your ancestry and royal connections', 'that might be our ancestry and royal connections', '人称前后不一：上句是 a part of us / we deserve'),
('s14', 'what you do for a living', 'what we do for a living', '人称前后不一：同上'),
('s15', 'In Western countries, at least—poor mental health', 'In Western countries, at least, poor mental health', '插入语 at least 以逗号开头就要以逗号结束'),
('s15', 'facilitate community participation—educational programs and interventions', 'facilitate community participation, and educational programs and interventions', '破折号表示同位，但 educational programs 不是 community participation，而是另一项建议'),
('s15', 'people do not need to own, but rather access things', 'people do not need to own, but rather access, things', '插入的对比成分 but rather access 两侧逗号成对'),
('s16', 'requires more than a vision, it requires a workforce', 'requires more than a vision; it requires a workforce', '逗号连接两个独立分句（comma splice）'),
('s16', 'compresses space, and unlike reality, is specifically designed', 'compresses space, and, unlike reality, is specifically designed', '插入语 unlike reality 两侧逗号成对'),
('s16', 'enable them to rethink their mental models, enable them to break free', 'enable them to rethink their mental models, break free', '三个并列动词 rethink / break free / embrace 共用 enable them to，原文第三项不平行'),
('s16', 'As such, an intervention like a simulation', 'Therefore, an intervention like a simulation', 'as such 需要名词先行词，这里表“因此”'),
('s17', 'They even sacrifice a good salary', 'Passionate workers even sacrifice a good salary', '上句的 they 指雇主，这里的 They 指代错位'),
('s17', 'career counselors who promote', 'career counselors that promote', '先行词包含机构（colleges, workplaces），用 that'),
('s18', 'test scores equal to their peers who have no absences', 'test scores equal to those of their peers who have no absences', '比较对象错位：分数与同龄人比'),
('s18', 'pressuring schools who serve them', 'pressuring schools that serve them', 'schools 用 that'),
('s19', 'small study groups, or whatever the teachers as a team agree', 'small study groups, and whatever the teachers as a team agree', 'between … and，不能 between … or'),
('s20', 'or whether cognitive strategy is more logical or free spirited or creative', 'or whether one’s cognitive strategy is more logical or free-spirited or creative', 'strategy 可数需限定词；free-spirited 是合成形容词'),
('s21', 'But the way they applied the principle', 'But the way they apply the principle', '时态与上句一般现在时一致'),
('s21', 'than you suppose', 'than we suppose', '同一句里 we → you 人称不一'),
('s21', 'The hypothesis is the commonly pleasing features', 'The hypothesis is that the commonly pleasing features', '表语从句需要 that'),
('s21', 'has to do more with elements of style, rather than “behavioral consequences”', 'has more to do with elements of style than with “behavioral consequences”', 'more … rather than 混用两种结构；应为 have more to do with … than with'),
('s21', 'evaluate environment, situations, and people', 'evaluate environments, situations, and people', '可数名词单数无冠词，与并列项一致用复数'),
('s21', 'Statements, like “beauty is in the eye of the beholder (观看者)”, are rarely questioned.', 'Statements like “beauty is in the eye of the beholder (观看者)” are rarely questioned.', '逗号使 like 短语变成非限制性，意思变成“所有说法都很少被质疑”'),
('s21', 'This is why it’s important to experience diverse cultures and their artifacts because it opens us up', 'This is why it’s important to experience diverse cultures and their artifacts: doing so opens us up', 'This is why … because 原因说了两遍；it 无先行词'),
('s22', 'closely-knit communities, sense of belonging', 'closely knit communities, a sense of belonging', '-ly 副词构成的复合修饰语不加连字符；sense 在此可数，需要 a'),
('s22', 'scarce attention is paid', 'scant attention is paid', '固定搭配 scant attention'),
('s22', 'among these changes; or should it at all?', 'among these changes—or should it at all?', '分号不能接在问句后面'),
('s22', 'introduced once foreign cultures', 'introduced once-foreign cultures', '前置复合修饰语加连字符，否则读成 introduced once'),
('s23', 'the public agenda, have become', 'the public agenda have become', '逗号隔开了主语和谓语'),
('s23', 'to suit the accepted beauty ideal such as editing the image, choosing the ideal filter, the right background.', 'to suit the accepted beauty ideal, such as editing the image or choosing the ideal filter and the right background.', 'such as 举的是工具功能的例子，不是 beauty ideal 的例子，需逗号；列举缺连词、结构不平行'),
('s24', 'Take hide-and-seek for example, which is a simulation', 'Take hide-and-seek, for example, which is a simulation', 'for example 两侧逗号成对，否则 which 像在修饰 example'),
('s25', '“Without my job I don’t know who I am,” is a sentence', '“Without my job I don’t know who I am” is a sentence', '引语是主语，逗号隔开了主语和谓语'),
('s25', 'eliminate uncertainty in our lives at some level we have to manage', 'eliminate uncertainty in our lives, at some level we have to manage', '长状语从句后加逗号，否则 at some level 被读进从句'),
('s25', 'asks us “what do you do?” we nearly always', 'asks us “What do you do?” we nearly always', '直接引语的问句首字母大写'),
('s25', 'may lead us into new sectors it is ever more important to challenge our sense of self and explore whether you can create a new experience of your identity by changing the beliefs you hold about yourself in order to expand your career options', 'may lead us into new sectors, it is ever more important to challenge our sense of self and explore whether we can create a new experience of our identity by changing the beliefs we hold about ourselves in order to expand our career options', '同一句中 us/our 与 you/your 混用（全文以 we 为主）；长状语从句后加逗号'),
('s26', '“Its political consequences are anything but trivial”.', '“Its political consequences are anything but trivial.”', '引语是完整句子，句号放在引号内'),
('s26', 'heavy viewers of rags-to-riches programmes or frequent viewers had', 'heavy or frequent viewers of rags-to-riches programmes had', '结构混乱：or frequent viewers 悬在后面'),
('s28', 'whether you’re a designated competent person', 'whether they’re a designated competent person', '同句前面用 they，人称不一'),
('s28', 'at a leadership level it creates the precedent', 'at a leadership level, it creates the precedent', '长 When 从句后加逗号'),
('s28', 'educate everyone within the organization that they are obliged', 'teach everyone within the organization that they are obliged', 'educate 不接 sb + that 从句'),
('s29', 'from the exactly same location', 'from exactly the same location', '语序：exactly the same'),
('s30', 'that the origin of the word sarcasm derives from', 'that the word sarcasm derives from', '主谓不搭：是这个词源自希腊语，不是“词源源自”'),
('s30', 'Greek word “sarkazein” which literally means', 'Greek word “sarkazein,” which literally means', '非限制性定语从句前加逗号'),
('s30', 'sarcasm is easy while true, harmless wit takes talent', 'sarcasm is easy, while true, harmless wit takes talent', '表对比的 while 连接两个独立分句，前加逗号'),
('s30', 'when a person consistently acts sarcastically it may only serve', 'when a person consistently acts sarcastically, it may only serve', '长 when 从句后加逗号'),
('s31', 'dating back to the middle ages.', 'dating back to the Middle Ages.', '历史时期专名大写'),
('s32', 'certain social discrepancies', 'certain social disparities', '群体间的不平等用 disparities'),
('s32', 'To benefit both researchers and the communities, the need', 'For the benefit of both researchers and the communities, the need', '悬垂不定式：need 不能 benefit'),
('s33', 'As it has often been pointed out, however', 'As has often been pointed out, however', 'as 从句里 as 作主语，不再加 it'),
('s33', 'After studying dozens of such cultures, Mead’s final conclusion was that', 'After studying dozens of such cultures, Mead came to the final conclusion that', '悬垂结构：conclusion 不能 study cultures'),
('s33', 'placed on competition as opposed to other values, such as cooperation—by various cultures', 'placed on competition—as opposed to other values, such as cooperation—by various cultures', '后面的破折号没有成对的前半'),
('s33', 'a phrase Darwin himself never used', 'a phrase Darwin himself did not coin', '事实错误：该说法由 Herbert Spencer 首创，达尔文在《物种起源》第 5 版（1869）中也用过'),
('s33', 'the Zuni Indians of Arizona', 'the Zuni Indians of New Mexico', '事实错误：祖尼人（Zuni Pueblo）在新墨西哥州'),
('s34', 'switch off—and for those living in digital exclusion to be able to switch on in the first place', 'switch off—and that those living in digital exclusion are able to switch on in the first place', '与前面的 that 从句平行'),
('s34', '(恶意挑衅的贴子)', '(恶意挑衅的帖子)', '中文注释错字：网上发的帖子是“帖”'),
('s34', 'for my mental health,” says she.', 'for my mental health,” she says.', '代词作主语时不倒装'),
('s35', 'Based on their results, the team concludes', 'On the basis of their results, the team concludes', '悬垂：based on 修饰的是主语 the team'),
('s37', 'electronically-controlled doors', 'electronically controlled doors', '-ly 副词复合修饰语不加连字符'),
('s37', 'are communicated and this could prevent', 'are communicated, and this could prevent', '两个独立分句之间加逗号'),
('s37', 'your volume and tone of voice, even if you do not dominate conversations', 'your volume and tone of voice, and even whether you dominate conversations', '逻辑：列举的是徽章能检测的内容，even if you do not… 讲不通'),
('s37', 'workers would opt to have a chip inserted', 'workers will opt to have a chip inserted', '与 there will probably be 的真实将来时一致'),
('s38', 'marketing culture we need to make a start somewhere', 'marketing culture, we need to make a start somewhere', '长让步从句后加逗号'),
('s38', '“pester power” or the ability of children', '“pester power”, or the ability of children', 'or 表“即”，前加逗号'),
('s40', 'one of those key things that makes food', 'one of those key things that make food', 'that 指代复数 things'),
('s40', 'the industry’s dependence on making their products', 'the industry’s dependence on making its products', '指代单数 the industry'),
('s40', 'the memories that we have for their products', 'the memories that we have for its products', '指代单数 the food industry（同句 spends 为单数）'),
('s40', 'One of the reasons I came to think', 'One of the reasons Moss came to think', '全文用第三人称叙述 Moss，这里的 I 无所指（未加引号的莫斯原话）'),
('s41', 'Progress in International Literacy Study', 'Progress in International Reading Literacy Study', '专有名称错误（PIRLS）'),
('s41', 'EdWeek Research Centre', 'EdWeek Research Center', '机构专名'),
('s43', 'one of these wonder materials that has been made', 'one of these wonder materials that have been made', 'that 指代复数 materials'),
('s44', 'more heart disease, metabolic disease and often die', 'more heart disease and metabolic disease and often die', '并列结构错误'),
('s45', 'exception: Live video chat.', 'exception: live video chat.', '冒号后是名词短语，不大写'),
('s45', 'AAP still says no screens at all are the best idea', 'the AAP still says no screens at all is the best idea', 'AAP 前加 the（与第 6 段一致）；no screens at all 作为一个主张，谓语用单数'),
('s45', 'For this age group, AAP recommends', 'For this age group, the AAP recommends', 'AAP 前加 the'),
('s45', 'they want care-givers', 'it wants care-givers', '指代 the AAP（单数）'),
('s45', 'observational research that infants', 'observational research showing that infants', 'research 不直接接同位语从句'),
('s45', '“Face time doesn’t count”', '“FaceTime doesn’t count”', '指视频通话应用 FaceTime；Face time 是“面对面时间”，意思相反'),
('s46', 'The Us government’s', 'The US government’s', '缩写大写'),
('s46', 'free reign', 'free rein', '习语 free rein'),
('s46', 'Some in US Congress have gone', 'Some in the US Congress have gone', 'the US Congress'),
('s46', 'is commendable but is this really the solution', 'is commendable, but is this really the solution', 'but 连接两个较长的分句，前加逗号'),
('s46', 'And, students will feel', 'And students will feel', '句首并列连词后不加逗号'),
('s47', 'fertilisers used in agriculture which increased', 'fertilisers used in agriculture, which increased', '非限制性定语从句前加逗号'),
('s47', 'both to alleviate poverty and preserve the environment', 'both to alleviate poverty and to preserve the environment', 'both … and 前后平行'),
('s47', 'marine eco-systems', 'marine ecosystems', '标准拼写 ecosystem'),
('s47', 'Subsequent efforts to remedy the environment', 'Subsequent efforts to remedy the damage', 'remedy 的宾语应是问题、损害'),
('s48', 'self-esteem but more with the fact', 'self-esteem and more with the fact', 'less … and more …'),
('s48', 'which swells our self-respect, people will try', 'which swells their self-respect, people will try', '人称不一'),
('s48', 'it neutralizes the existence of negative motivation', 'it neutralizes the effects of negative motivation', 'neutralize 的对象是作用、影响，不是“存在”'),
('s49', 'communication expertise-imagine', 'communication expertise—imagine', '这里应是破折号'),
('s49', 'at all levels of public education with most secondary schools offering', 'at all levels of public education, with most secondary schools offering', '独立结构前加逗号'),
('s50', 'Instead of shying away from the idea of this bleak future, the best approach to take is one of optimism and curiosity.', 'Instead of shying away from the idea of this bleak future, we would do best to approach it with optimism and curiosity.', '悬垂结构：shying away 的主语不能是 the best approach'),
('s50', 'American idol star', 'American Idol star', '节目名 American Idol'),
('s50', 'considered as too precious', 'considered too precious', 'consider + 形容词，不加 as'),
('s50', 'Contrary to seeing AI as a tool', 'Rather than seeing AI as a tool', 'contrary to 接观点、预期类名词，不接动作'),
('s50', 'It can serve as a source of inspiration', 'AI can serve as a source of inspiration', 'It 会被理解成上句的 Taryn’s story'),
('s50', 'Using AI in the creation of music is perceived by some as a helpful tool', 'AI is perceived by some as a helpful tool in the creation of music', '“使用 AI”不能是工具，AI 才是工具'),
('s51', 'Research Organization', 'Research Organisation', 'CSIRO 官方名称拼作 Organisation'),
('s51', 'with existing beliefs as an application of common sense', 'with existing beliefs for an application of common sense', 'mistake A for B'),
('s52', 'low-and middle-income', 'low- and middle-income', '悬空连字符后要空格'),
('s53', 'Occupation and social economic status', 'Occupation and socio-economic status', '规范术语 socio-economic（第 55 题选项也是 socio-economic）'),
('s53', 'similar social economic situations', 'similar socio-economic situations', '同上'),
('s54', '25—54', '25–54', '年龄范围用短横线'),
('s54', 'rapidly-changing', 'rapidly changing', '-ly 副词复合修饰语不加连字符'),
('s55', 'Fm not referring', 'I’m not referring', '试卷印成 Fm，应为 I’m'),
('s55', 'less about what they can contribute but more about', 'less about what they can contribute and more about', 'less about … and more about'),
('s55', 'They’d then go further', 'He or she will then go further', '上句是 He or she will，这里 They’d 人称和情态都不一致'),
('s55', 'heightened motivation, to perform well.', 'heightened motivation, performing well.', '与上句 keep them motivated 平行（keep them … performing well）'),
('s55', 'This thereby leads them', 'This leads them', 'thereby 与 This 重复'),
('s55', 'warning no one single response', 'warning that no one single response', '不加 that 会读成 warning no one（谁也不警告）'),
('s55', 'between the privileges they feel they’re owed and their inflated sense of self-worth, they', 'between the privileges they feel they’re owed and their actual performance, and of their inflated sense of self-worth, they', '逻辑：上段说这种期望与能力、表现无关，落差应在“自认应得”与“实际表现”之间；自视过高是另一个原因'),
('s56', 'classmates, appearances', 'classmates’ appearances', '所有格撇号印成了逗号'),
('s56', 'we entertain each other', 'they entertain each other', '主语是 Americans，引语接着用第三人称（波兹曼原文也是 they）'),
('s56', 'They don’t exchange ideas, they exchange images', 'They don’t exchange ideas; they exchange images', '逗号连接两个独立分句（波兹曼原文用分号）'),
('s56', 'They do not argue with propositions, they argue', 'They do not argue with propositions; they argue', '逗号连接两个独立分句（波兹曼原文用分号）'),
('s56', 'abuses of logic and common sense. It also means to weigh ideas', 'abuses of logic and common sense.” It also enables us “to weigh ideas', 'It also means 的主语（原书的 to engage the written word）被删掉了，It 无所指；改为承接上句 text enables us'),
('s57', 'consumers, minds', 'consumers’ minds', '所有格撇号印成了逗号'),
('s57', 'detrimental both to the consumers', 'detrimental to both the consumers', 'both … and 前后平行'),
('s57', 'and ultimately, more costly', 'and, ultimately, more costly', '插入语 ultimately 两侧逗号成对'),
('s57', 'on their milk, despite the fact that all milk is naturally GMO-free, another label that creates unnecessary fear around food.', 'on their milk—another label that creates unnecessary fear around food—despite the fact that all milk is naturally GMO-free.', '同位语位置错误：another label 说的是 non-GMO 标签，原文紧跟在 GMO-free 后面'),
('s57', '‘no sugar,’ or', '‘no sugar’ or', 'A or B or C 中间不加逗号'),
('s58', 'Linkedln', 'LinkedIn', '公司名拼错'),
('s58', 'considered Unethical or even illegal', 'considered unethical or even illegal', '句中普通形容词不大写'),
('s58', 'But before using social media to screen job candidates, consulting with management and legal teams beforehand is essential', 'But before employers use social media to screen job candidates, consulting with management and legal teams is essential', '悬垂：using 的逻辑主语不是 consulting；before … beforehand 重复'),
('s58', 'they will never ask for passwords, be consistent,', 'they will never ask for passwords; they should also be consistent,', '并列动词紧接在 will never 后，会读成“绝不保持一致”'),
('s58', 'gender, religion, etc., and that could bias', 'gender, and religion, and that could bias', 'like … etc. 重复（like 已表示举例）'),
]
E = json.loads(Path('六级/tools/原文订正.json').read_text('utf-8'))
n = 0
for pid, o, new, why in D:
    t = P[pid]
    E.setdefault(t, [])
    if not any(e['old'] == o for e in E[t]):
        E[t].append({'type': '原文错误', 'old': o, 'new': new, 'why': why}); n += 1
Path('六级/tools/原文订正.json').write_text(json.dumps(E, ensure_ascii=False, indent=1) + '\n', 'utf-8')
print('added', n, 'total', sum(len(v) for v in E.values()))
